#!/bin/bash
dir=$(pwd)
IFS='/' read -r -a array <<< "$dir"
contract_name="${array[-1]}"

export LD_LIBRARY_PATH=/home/okayjava/eos/eos/contracts/eosiolib:/usr/local/eosio/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/home/okayjava/eos/eos/contracts/eosiolib:/usr/local/eosio/bin
eosiocpp -o ${contract_name}.wast ${contract_name}.cpp
eosiocpp -g ${contract_name}.abi ${contract_name}.cpp

